baseURL = "https://www.geteduroam.app"
languageCode = "en-gb"
title = "geteduroam"
theme = "hugo-book"
enableGitInfo = true

[params]
BookTheme = 'auto' # light/dark/auto
BookToC = true
BookSection = '*'
BookDateFormat = 'Jan, 2006'
BookLogo = 'geteduroam-inverse.png'
BookSearch = true
BookComments = false

BookRepo = 'https://github.com/geteduroam/geteduroam.github.io'
BookCommitPath = 'commit'
BookEditPath = 'edit/main'
